name: Tests CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove package-lock.json and node_modules
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Install @rollup/rollup-linux-x64-gnu
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: Run Vitest tests
        run: npm run test
